#!/usr/bin/env python


import os
import rospy
from std_msgs.msg import String


def stringCallback(msg):
    rospy.loginfo('[espeak node] Speaking the following string: ' + msg.data)
    os.system('espeak '+ '"' + msg.data + '"')

if __name__=='__main__':
    rospy.init_node('espeak')

    string_sub = rospy.Subscriber('/espeak/string', String, stringCallback)

    rospy.spin()